var User = require('./User')

const random1 = new User(3, 6, "Tina", 28)
const random2 = new User(41, 60, "Bart", 12)
const random3 = new User(616, 1160, "Prison Mike", 10000)

console.log(random1.add(random1.num1, random1.num2))
console.log(random1.subtract(random1.num1, random1.num2))
console.log(random1.multiply(random1.num1, random1.num2))
console.log(random1.divide(random1.num1, random1.num2))
console.log(random1.greeting())
console.log(random1.numbersToString())
console.log("------------------------------------------------")
console.log(random2.add(random2.num1, random2.num2))
console.log(random2.subtract(random2.num1, random2.num2))
console.log(random2.multiply(random2.num1, random2.num2))
console.log(random2.divide(random2.num1, random2.num2))
console.log(random2.greeting())
console.log(random2.numbersToString())
console.log("-------------------------------------------------")
console.log(random3.add(random3.num1, random3.num2))
console.log(random3.subtract(random3.num1, random3.num2))
console.log(random3.multiply(random3.num1, random3.num2))
console.log(random3.divide(random3.num1, random3.num2))
console.log(random3.greeting())
console.log(random3.numbersToString())